name: Conventional Commit Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Check Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webiny/action-conventional-commits@v1.1.0